parameters:
- name: testAssemblyVer2
  type: string
- name: searchFolder
  type: string
- name: filePath
  type: string

stages:
  - stage: Test
    displayName:  Test
    dependsOn:
      CreateAutomationDatabaseTest
    variables:
      - group: Test Shared Resources
      - group: Common Shared Resources
    jobs:
      - template: ../jobs/resac-test.yml
        parameters:
          testAssemblyVer2: '${{parameters.testAssemblyVer2}}'
          searchFolder: '${{parameters.searchFolder}}'
          filePath: '${{parameters.filePath}}'