parameters:
- name: testAssemblyVer2
  type: string
- name: searchFolder
  type: string
- name: filePath
  type: string
- name: stageName
  type: string
- name: deploymentDependencyName
  type: string

stages:
  - stage: ${{parameters.stageName}}
    displayName:  'Environment - ${{parameters.stageName}}'
    dependsOn: '${{parameters.deploymentDependencyName}}'      
    variables:
      - group: Test Shared Resources
      - group: Common Shared Resources
    jobs:
      - template: ../jobs/resac-test.yml
        parameters:
          testAssemblyVer2: '${{parameters.testAssemblyVer2}}'
          searchFolder: '${{parameters.searchFolder}}'
          filePath: '${{parameters.filePath}}'