parameters:
- name: ServiceConnection
  type: string
- name: SharedSqlServerFQDN
  type: string
- name: DatabaseName
  type: string
- name: SharedSqlServerUsername
  type: string
- name: SharedSqlServerPassword
  type: string
- name: artifactname
  type: string
- name: dacpacklocation
  type: string

stages:
- stage: CreateAutomationDatabaseTest
  displayName: Deploy Automation database
  dependsOn:
    buildstage
  variables:
    - group: Test Shared Resources
    - group: Common Shared Resources
  jobs:      
    - template: ../jobs/resac-deploy-database.yml