resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    - repository: RESAC
      type: github
      endpoint: SkillsFundingAgency
      name: SkillsFundingAgency/tl-results-and-certification
trigger:
  batch: true
  branches:
    include:
      - "*"
pr: none

      
variables:
  buildConfiguration: 'release'
  MSBUILDSINGLELOADCONTEXT: 1
      
stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        pool:
          name: 'Azure Pipelines'
          vmImage: 'windows-2019'
        workspace:
          clean: all
        steps:
          - task: gittools.gitversion.gitversion-task.GitVersion@5
            displayName: GitVersion
          
          - task: UseDotNet@2
            displayName: 'Use .NET Core SDK 3.1.100'
            inputs:
              packageType: sdk
              version: 3.1.100
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - task: DotNetCoreCLI@2
            displayName: dotnet restore
            inputs:
              command: restore
              projects: 'src/**/*.csproj'
              noCache: true
          
          - task: DotNetCoreCLI@2
            displayName: dotnet build
            inputs:
              projects: 'src/**/*.csproj'
              arguments: '--configuration $(buildConfiguration) --no-restore'
              
          - task: DotNetCoreCLI@2
            displayName: 'dotnet pack'
            inputs:
              command: 'pack'
              projects: 'src/**/*.csproj'
              packDirectory: '$(build.artifactstagingdirectory)/publish'
              arguments: '--configuration $(buildConfiguration) --no-restore'
          
          - task: DotNetCoreCLI@2
            displayName: 'dotnet publish'
            inputs:
              command: publish
              publishWebProjects: false
              zipAfterPublish: false
              projects: 'src/**/*Automation.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/tests --no-restore --no-build'
          
          # - task: VSBuild@1
          #   displayName: 'Build DACPAC'
          #   inputs:
          #     solution: 'src/Sfa.Tl.ResultsAndCertification.Database/Sfa.Tl.ResultsAndCertification.Database.sqlproj'
          #     platform: '$(buildPlatform)'
          #     configuration: '$(buildConfiguration)'
          #     msbuildArgs: '/p:PackageLocation="$(build.artifactstagingdirectory)/publish"'
          
          - task: CopyFiles@2
            displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
            inputs:
              Contents: |     
                src/**/*.ps1
              TargetFolder: '$(build.artifactstagingdirectory)'
              OverWrite: true
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              pathtoPublish: '$(build.artifactstagingdirectory)'



