schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
      - feature/*
resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

    - repository: RESAC
      type: github
      endpoint: S126-Tlevelservice
      name: SkillsFundingAgency/tl-results-and-certification
      ref: feature/sprint-18

    - repository: devopsTools
      type: github
      endpoint: DFE-Digital
      name: DFE-Digital/operations-devops-tools

    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates
trigger:
  batch: true
  branches:
    include:
      - "*"
pr: none

variables:
  buildConfiguration: 'release'
  MSBUILDSINGLELOADCONTEXT: 1
  buildPlatform: 'anycpu'
  applicationName: 'resac automation'

stages:  
  - template: ./yaml/stages/resac-build.yml
    parameters: 
      buildConfiguration: $(buildConfiguration)
      buildPlatform: $(buildPlatform)
      ArtifactName: 'appdrop'

  - template: ./yaml/stages/resac-deploy-database.yml
    parameters:
      ServiceConnection: $(ServiceConnection)
      SharedSqlServerFQDN: $(SharedSqlServerFQDN)
      DatabaseName: $(AutomationDatabaseName)
      SharedSqlServerUsername: $(SharedSqlServerUsername)
      SharedSqlServerPassword: $(SharedSqlServerPassword)
      artifactname: 'sqldrop' 
      dacpacklocation: '$(System.ArtifactsDirectory)/sqldrop/src/Sfa.Tl.ResultsAndCertification.Database/bin/Release/Sfa.Tl.ResultsAndCertification.Database.dacpac'
  
  - stage: Test
    displayName:  Test
    dependsOn:
      CreateAutomationDatabaseTest
    variables:
      - group: Test Shared Resources
      - group: Common Shared Resources
    jobs:
      - job: runTests
        displayName: Run the automation tests
        pool:
            name: 'Azure Pipelines'
            vmImage: 'windows-2019'
        steps:
          - checkout: devopsTools
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'appdrop'
              downloadPath: '$(System.ArtifactsDirectory)'          
          
          - task: Tokenization@2
            displayName: 'Tokenization: Transform file *.json'
            inputs:
              SourcePath: '$(System.ArtifactsDirectory)/appdrop/tests'
              TargetFileNames: '*.json'
          
          - task: VSTest@2
            displayName: 'VsTest - Test Execution'
            inputs:
              testAssemblyVer2: '**\SFA.Tl.ResultsAndCertificationAutomation.dll'
              searchFolder: '$(System.ArtifactsDirectory)/appdrop/tests/Sfa.Tl.ResultsAndCertificationAutomation/'
              runInParallel: false
              rerunFailedTests: true
            continueOnError: true
          
          - task: PowerShell@2
            displayName: 'Check .trx File Exists'
            inputs:
              targetType: filePath
              filePath: '$(System.ArtifactsDirectory)/appdrop/src/Sfa.Tl.ResultsAndCertificationAutomation/Check-TestResults.ps1'
              arguments: '-SourcePath "$(Agent.TempDirectory)/testresults"'

  - stage: PP
    displayName: Pre-Production
    dependsOn:
      buildstage
    variables:
      - group: PreProd Shared Resources
      - group: Common Shared Resources
    jobs:
    - job: runTests
      displayName: Run the automation tests
      pool:
          name: 'Azure Pipelines'
          vmImage: 'windows-2019'
      steps:
        - checkout: devopsTools
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'appdrop'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'sqldrop'
            downloadPath: '$(System.ArtifactsDirectory)'

        - task: Tokenization@2
          displayName: 'Tokenization: Transform file *.json'
          inputs:
            SourcePath: '$(System.ArtifactsDirectory)/appdrop/tests'
            TargetFileNames: '*.json'

        - task: VSTest@2
          displayName: 'VsTest - Test Execution'
          inputs:
            testAssemblyVer2: '**\SFA.Tl.ResultsAndCertificationAutomation.dll'
            searchFolder: '$(System.ArtifactsDirectory)/appdrop/tests/Sfa.Tl.ResultsAndCertificationAutomation/'
            testFiltercriteria: 'TestCategory=SmokeTest'
            runInParallel: false
            rerunFailedTests: true
          continueOnError: true

        - task: PowerShell@2
          displayName: 'Check .trx File Exists'
          inputs:
            targetType: filePath
            filePath: '$(System.ArtifactsDirectory)/appdrop/src/Sfa.Tl.ResultsAndCertificationAutomation/Check-TestResults.ps1'
            arguments: '-SourcePath "$(Agent.TempDirectory)/testresults"'

      