parameters:
- name: buildConfiguration
  type: string
  default: 'Release'
- name: artifactname
  type: string

jobs:       
  - job: buildAppJob
    displayName: Build App Job
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2022'
    workspace:
      clean: all
    steps:
    - template: ../steps/resac-build.yml
      parameters:
        buildConfiguration: ${{parameters.buildConfiguration}}
        artifactname: ${{parameters.artifactname}}