parameters:
- name: buildConfiguration
  type: string
  default: 'Release'
- name: artifactname
  type: string

jobs:       
  - job: buildAppJob
    displayName: Build App Job
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    workspace:
      clean: all
    steps:
      - checkout: self
      
      - task: gittools.gitversion.gitversion-task.GitVersion@5
        displayName: GitVersion
      
      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: restore
          projects: 'src/**/*.csproj'
          noCache: true
      
      - task: DotNetCoreCLI@2
        displayName: dotnet build
        inputs:
          projects: 'src/**/*.csproj'
          arguments: '--configuration ${{parameters.buildConfiguration}} --no-restore'
          
      - task: DotNetCoreCLI@2
        displayName: 'dotnet pack'
        inputs:
          command: 'pack'
          projects: 'src/**/*.csproj'
          packDirectory: '$(build.artifactstagingdirectory)/publish'
          arguments: '--configuration ${{parameters.buildConfiguration}} --no-restore'
      
      - task: DotNetCoreCLI@2
        displayName: 'dotnet publish'
        inputs:
          command: publish
          publishWebProjects: false
          zipAfterPublish: false
          projects: 'src/**/*Automation.csproj'
          arguments: '--configuration ${{parameters.buildConfiguration}} --output $(build.artifactstagingdirectory)/tests --no-restore --no-build'
      
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          Contents: |     
            src/**/*.ps1
          TargetFolder: '$(build.artifactstagingdirectory)'
          OverWrite: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: '${{parameters.artifactname}}'
          publishLocation: 'Container'